### PR TITLE
[MNO-287] Change developer registration event description

### PR DESCRIPTION
**Pull request by hedudelgado**
@ouranos
I spotted a little bug on the code while testing it. This should fix it.

### CODE REVIEW

**Comment by hedudelgado** [comment]
@ouranos 
I had to squash the commits and a open a new and different PR to re-apply the commits that were reverted, otherwise they would not have been applied.

**Comment by ouranos** [comment]
Hi @hedudelgado I don't think you need this. Check with @x4d3.
Also could you find a better description for this event. Thanks

**Comment by x4d3** [comment]
confirm that the last argument of the function (metadata) is optional. The method will automatically use the to_audit_event of the user class.

**Comment by hedudelgado** [comment]
@ouranos

**Comment by ouranos** [comment]
@x4d3 see if the change is needed?
Also for the description, I'd put something like "User registered as developer" or "Developer registration" to keep it consistent with other events?

**Comment by x4d3** [comment]
I agree it is important to log the fact that a User registered as a developer. And I agree with the description "Developer registration""

**Comment by hedudelgado** [comment]
@ouranos

**Comment by ouranos** [comment]
Hi @x4d3 and @hedudelgado 

As mentioned above, we changed the method signature in `master` to be
```ruby
self.info(key, current_user_id, description, object, metadata = {})
``` 
So the metadata is optional and `object.to_audit_event` is called if metadata is not provided.

Please fix this PR to only amend the event description or explain how this is fixing a bug

Thanks

**Comment by ouranos** [comment]
Hi @x4d3 and @hedudelgado, could you look at the above? Thanks

**Comment by hedudelgado** [comment]
His @x4d3 and @ouranos , unable to reproduce the bug that I apparently had, I cleaned the commits up and only include the changes on the description.

**Pull request merged**
