### PR TITLE
Fix cache refresh when there's a marshalling error

### PR DESCRIPTION
**Pull request by ouranos**
@alachaum not super happy about this fix but it seems that Her is making the user a singleton in some cases.

@fgourichon that would fix the error at org creation

### CODE REVIEW

**Comment by ouranos** [comment]
@fgourichon Could you test that locally? I don't have the config for it

**Comment by fgourichon** [comment]
@ouranos not working for SSO...
Error is : 
```
undefined method `marshal_dump' for nil:NilClass
 module_eval <<-RUBY, __FILE__, __LINE__ + 1 
 def #{name}(*args, &block) 
 #{target_name}.send(#{name.inspect}, *args, &block) 
 end 
 RUBY 
 end 
```

```
her (0.7.6) lib/her/model/associations/association_proxy.rb:11:in `marshal_dump'
/home/fgourichon/.rvm/gems/ruby-2.3.1/bundler/gems/mno-enterprise-5f1025998c98/core/lib/her_extension/model/associations/association_proxy.rb:33:in `method_missing'
activesupport (4.2.7.1) lib/active_support/cache.rb:667:in `dump'
 
```

**Comment by ouranos** [comment]
@fgourichon Ok I've added NoMethodError too.

**Comment by alachaum** [comment]
Is it worth adding a retry? (Does it happen randomly?

Otherwise happy with the fix. Not ideal but at least it does the job.

**Comment by ouranos** [comment]
I don't think adding a retry will help with anything as we already reload the object before.
We can reproduce every time with specific workflow (impersonation or SSO from a specific vendor) but with different error for each workflow.
I have the feeling it has to do with the way Her manipulate the object or the associations but haven't been able to track it down.

**Pull request merged**
