### PR TITLE
[MNOE-44] Add SparkPost support

### PR DESCRIPTION
**Pull request by ouranos**
Add SparkPost support has a free alternative since:
> All Mandrill users will be required to have a paid monthly MailChimp account by April 27

### CODE REVIEW

**Comment by ouranos** [comment]
@alachaum @BrunoChauvet Could you have a look?

Do not merge yet, I'll do more testing.

**Comment by ouranos** [comment]
All templates migrated to the default SparkPost account.

I'll do full testing on an express instance with both providers.

**Comment by ouranos** [comment]
Test working with a local instance. I'll add some tooling to copy to provision new mandrill/sparkpost account.

**Comment by ouranos** [comment]
@BrunoChauvet final code review please?

**Comment by BrunoChauvet** [comment]
Looks good!

**Pull request merged**
